في عندي هي الداتا الفوتوسيشت محطوطين ب فولدرات من الداخل بدي احذف الفولدرات لحتى يصير الشخص عندما يضغط على جلسات التصوير يفتح له باقي الصور بدون مجلدات :           const portfolioData = {
            photosessions: {
                folders: {
                    "1": {
                        name: "1",
                        count: 24,
                        thumbnail: "photo-person/arena/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/arena/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/22.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/23.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/arena/24.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' }
                        ]
                    },
                    "2": {
                        name: "2",
                        count: 47,
                        thumbnail: "photo-person/lina/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/lina/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/22.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/23.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/24.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/25.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/26.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/27.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/28.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/29.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/30.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/31.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/32.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/33.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/34.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/35.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/36.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/37.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/38.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/39.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/40.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/41.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/42.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/43.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/44.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/45.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/46.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/lina/47.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' }
                        ]
                    },
                    "3": {
                        name: "3",
                        count: 9,
                        thumbnail: "photo-person/mavs/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/mavs/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/mavs/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },

                        ]
                    },
                    "4": {
                        name: "4",
                        count: 16,
                        thumbnail: "photo-person/metro/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/metro/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/metro/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },


                        ]
                    },
                    "5": {
                        name: "5",
                        count: 28,
                        thumbnail: "photo-person/nacta/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/nacta/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/22.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/23.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/24.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/25.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/26.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/27.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/nacta/28.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },


                        ]
                    },
                    "6": {
                        name: "6",
                        count: 21,
                        thumbnail: "photo-person/wedding/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/wedding/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/wedding/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                        ]
                    },
                    "7": {
                        name: "7",
                        count: 16,
                        thumbnail: "photo-person/rand/21.webp",
                        items: [
                            { type: 'image', src: 'photo-person/rand/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/22.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/23.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/24.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/25.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/26.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/27.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/rand/28.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                        ]
                    },
                    "2": {
                        name: "2",
                        count: 47,
                        thumbnail: "photo-person/masha/1.webp",
                        items: [
                            { type: 'image', src: 'photo-person/masha/1.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/2.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/3.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/4.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/5.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/6.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/7.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/8.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/9.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/10.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/11.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/12.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/13.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/14.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/15.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/16.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/17.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/18.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/19.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/20.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/21.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/22.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/23.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/24.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/25.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/26.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/27.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/28.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/29.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/30.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/31.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/32.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/33.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                            { type: 'image', src: 'photo-person/masha/34.webp', title: 'Портретная съёмка', desc: 'Студийная фотосессия' },
                        ]
                    },
                }
            },
            videos: {
                items: [ 
                    //{ type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1770485542/Video_2026-02-07_14-20-37_hpadop.mp4', title: 'Корпоративное видео', desc: 'Съёмка и монтаж' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1770485212/Video_2026-02-07_14-20-40_tkwz82.mp4', title: '3D-модель', desc: 'Коммерческий проект' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1770484776/video_2026-02-07_14-20-32_uxvgvg.mp4', title: 'реклама для маркетплейсов', desc: 'Процесс съёмки' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190319/Jewelry21_hdabd5.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Съёмочная площадка' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190499/Jewelry14_pl2cgy.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Художественное видео' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190501/Jewelry22_wwoc28.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Режиссёрская работа' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190514/Jewelry13_fmjn6s.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Мероприятия' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190572/Jewelry15_votuc9.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Дрон видео' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190607/Jewelry1_xzzysz.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Ускоренное видео' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190703/Jewelry3_cuykbc.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Motion graphics' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190869/Jewelry2_orwrsv.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Прямые трансляции' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772190979/Jewelry4_ubfcky.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Панорамная съёмка' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191039/Jewelry18_rrn6b7.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Корпоративное обучение' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191073/Jewelry16_r5qmno.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Motion graphics' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191091/Jewelry20_zhzuoo.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Прямые трансляции' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191097/Jewelry17_cz9bkc.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Панорамная съёмка' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191132/Jewelry5_px7ieg.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Корпоративное обучение' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191167/Jewelry6_cnovqg.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Motion graphics' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191347/Jewelry23_ge0ldg.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Прямые трансляции' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191403/Jewelry19_d6qfcl.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Панорамная съёмка' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191466/Jewelry10_go26hv.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Корпоративное обучение' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191495/Jewelry11_jjldaj.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Прямые трансляции' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191520/Jewelry7_py8myd.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Панорамная съёмка' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191547/Jewelry12_z2txxb.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Корпоративное обучение' },
                    { type: 'video', src: 'https://res.cloudinary.com/ddfw5wx6f/video/upload/v1772191775/Jewelry8_alhry7.mp4', title: 'Фотосъемка ювелирных изделий', desc: 'Motion graphics' }
                ]
            },
            products: {
                items: [
                    { type: 'image', src: 'photo-ads/1.webp', title: 'Предметная съёмка', desc: 'Коммерческая фотография' },
                    { type: 'image', src: 'photo-ads/3.webp', title: 'Каталожная съёмка', desc: 'E-commerce' },
                    { type: 'image', src: 'photo-ads/4.webp', title: 'Ювелирные изделия', desc: 'Макро съёмка' },
                    { type: 'image', src: 'photo-ads/5.webp', title: 'Косметика', desc: 'Бьюти продукты' },
                    { type: 'image', src: 'photo-ads/6.webp', title: 'Электроника', desc: 'Техника' },
                    { type: 'image', src: 'photo-ads/7.webp', title: 'Одежда', desc: 'Fashion products' },
                    { type: 'image', src: 'photo-ads/8.jpg', title: 'Обувь', desc: 'Продуктовая съёмка' },
                    { type: 'image', src: 'photo-ads/9.jpg', title: 'Аксессуары', desc: 'Детали' },
                    { type: 'image', src: 'photo-ads/10.jpeg', title: 'Часы', desc: 'Luxury products' },
                    { type: 'image', src: 'photo-ads/11.webp', title: 'Парфюмерия', desc: 'Ароматы' },
                    { type: 'image', src: 'photo-ads/12.webp', title: 'Еда', desc: 'Food photography' },
                    { type: 'image', src: 'photo-ads/13.webp', title: 'Напитки', desc: 'Beverage' },
                    { type: 'image', src: 'photo-ads/14.jpg', title: 'Упаковка', desc: 'Packaging' },
                    { type: 'image', src: 'photo-ads/15.jpg', title: 'Книги', desc: 'Print products' },
                    { type: 'image', src: 'photo-ads/16.jpg', title: 'Гаджеты', desc: 'Tech products' },
                    { type: 'image', src: 'photo-ads/17.png', title: 'Спорттовары', desc: 'Sports equipment' },
                    { type: 'image', src: 'photo-ads/18.png', title: 'Дом и интерьер', desc: 'Home decor' },
                    { type: 'image', src: 'photo-ads/19.png', title: 'Детские товары', desc: 'Kids products' },
                    { type: 'image', src: 'photo-ads/20.png', title: 'Автотовары', desc: 'Auto accessories' },
                    { type: 'image', src: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30', title: 'Минимализм', desc: 'White background' }
                ]
            }
        };
